services:
  mongodb:
    image: mongo:8.0.15
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: "user_micro_services"
      MONGO_INITDB_ROOT_PASSWORD: "QHSfHYu4Qc0X7Pf3XCTRCABfyPNkbanc"
      MONGO_INITDB_DATABASE: "db_micro_services"

    ports:
      - "27017:27017"

    volumes:
      - /opt/volumes/mongodb/data:/data/db

    networks:
      - mongo_network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet -u user_micro_services -p QHSfHYu4Qc0X7Pf3XCTRCABfyPNkbanc --authenticationDatabase admin --eval \"db.adminCommand('ping').ok\" | grep 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

networks:
  mongo_network:
    driver: bridge
  

