#!/usr/bin/env bash
set -eu

ELASTICSEARCH_URL="${TODO_ELASTICSEARCH_URL:-${ELASTICSEARCH_URL:-http://localhost:9200}}"
ELASTICSEARCH_USERNAME="${TODO_ELASTICSEARCH_USERNAME:-${ELASTICSEARCH_USERNAME:-elastic}}"
ELASTICSEARCH_PASSWORD="${TODO_ELASTICSEARCH_PASSWORD:-${ELASTICSEARCH_PASSWORD:-}}"

if [ -z "$ELASTICSEARCH_PASSWORD" ]; then
  echo "Set TODO_ELASTICSEARCH_PASSWORD or ELASTICSEARCH_PASSWORD."
  exit 2
fi

curl -fsS -u "$ELASTICSEARCH_USERNAME:$ELASTICSEARCH_PASSWORD" "$ELASTICSEARCH_URL/_cluster/health?pretty"
echo
curl -fsS -u "$ELASTICSEARCH_USERNAME:$ELASTICSEARCH_PASSWORD" "$ELASTICSEARCH_URL/_cat/indices/*apm*,logs-*?v" || true
